### ISSUE TITLE
Xcode error

### ISSUE THREAD

**Issue by abhishekpixelgrand** [algomystic/TheParallaxView#16] opened 2018-03-12 10:57 UTC
throwing this exception in xcode debug view while running in iphone X
"terminating with uncaught exception of type NSException"

application is closing after showing made with unity loading screen

**Comment by algomystic** [comment] 2018-03-13 18:33
Cannot reproduce. Probably something wrong in your installation of xcode or unity. Closing

**Closed by algomystic** 2018-03-13 18:33 UTC
